$(document).ready(function(){
    $("#first").click(function(){
      $(".option1").slideToggle("slow");
      $(".option2").hide();
      $(".option3").hide();
      $(".option4").hide();
    });
  });
  $(document).ready(function(){
    $("#second").click(function(){
      $(".option2").slideToggle("slow");
      $(".option1").hide();
      $(".option3").hide();
      $(".option4").hide();
    });
  });
  $(document).ready(function(){
    $("#third").click(function(){
      $(".option3").slideToggle("slow");
      $(".option2").hide();
      $(".option1").hide();
      $(".option4").hide();
    });
  });
  $(document).ready(function(){
    $("#fourth").click(function(){
      $(".option4").slideToggle("slow");
      $(".option2").hide();
      $(".option3").hide();
      $(".option1").hide();
    });
  });